name: Deploy to Netlify

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test -- --coverage --watchAll=false
    
    - name: Build application
      run: npm run build
      env:
        REACT_APP_NARA_API_KEY: ${{ secrets.REACT_APP_NARA_API_KEY }}
        REACT_APP_OPENAI_API_KEY: ${{ secrets.REACT_APP_OPENAI_API_KEY }}
        REACT_APP_EMAIL_API_KEY: ${{ secrets.REACT_APP_EMAIL_API_KEY }}
        REACT_APP_GOOGLE_SHEETS_CLIENT_EMAIL: ${{ secrets.REACT_APP_GOOGLE_SHEETS_CLIENT_EMAIL }}
        REACT_APP_GOOGLE_SHEETS_PRIVATE_KEY: ${{ secrets.REACT_APP_GOOGLE_SHEETS_PRIVATE_KEY }}
        REACT_APP_JWT_SECRET: ${{ secrets.REACT_APP_JWT_SECRET }}

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build application
      run: npm run build
      env:
        REACT_APP_NARA_API_KEY: ${{ secrets.REACT_APP_NARA_API_KEY }}
        REACT_APP_OPENAI_API_KEY: ${{ secrets.REACT_APP_OPENAI_API_KEY }}
        REACT_APP_EMAIL_API_KEY: ${{ secrets.REACT_APP_EMAIL_API_KEY }}
        REACT_APP_GOOGLE_SHEETS_CLIENT_EMAIL: ${{ secrets.REACT_APP_GOOGLE_SHEETS_CLIENT_EMAIL }}
        REACT_APP_GOOGLE_SHEETS_PRIVATE_KEY: ${{ secrets.REACT_APP_GOOGLE_SHEETS_PRIVATE_KEY }}
        REACT_APP_JWT_SECRET: ${{ secrets.REACT_APP_JWT_SECRET }}
    
    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v2.0
      with:
        publish-dir: './build'
        production-branch: main
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Deploy from GitHub Actions"
        enable-pull-request-comment: false
        enable-commit-comment: true
        overwrites-pull-request-comment: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
